
trigger:
- main

pool: linux

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker-weby'
    repository: 'weby'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-weby'
    repository: 'ssanthoshkalam/weby'
    command: 'push'
    tags: 'latest'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/'
    Contents: 'deployment.yaml'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'manifestfile'
    publishLocation: 'Container'