version: '3.1'

services:
  weby:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: weby_webapp
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - webydb
    volumes:
      - ".:/weby"
    #command: ["init"] # comment this when init not needed.
    environment:
      ENV RAILS_ENV: development
      PG_DB: weby
      PG_USER: weby
      PG_PASS: weby
      PG_HOST: webydb
      SECRET_KEY_BASE: d42f89e05bca1a10b56952a91911aef765832ae23cb10c9af6729e3ddd3bed56cfadadd50353278890343719bfa3bbc319920573d3a3f812c32bd5b0d3fc6702

  webydb:
    image: postgres
    container_name: weby
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: weby
      POSTGRES_USER: weby
      POSTGRES_DB: weby